### PR TITLE
PTUR-3 newsletter layout body section

### PR DESCRIPTION
**Pull request by muhammad-zulfa**
- [x] newsletter layout (body section)
- [x] newsletter layout (conclusion)

## References
JIRA: https://polyrific.atlassian.net/browse/PTUR-3?atlOrigin=eyJpIjoiNWIxMTYyYWU2YjliNGZiOWJjYjZiZTBiNTljN2UwZTQiLCJwIjoiaiJ9

image
image
image

### CODE REVIEW

**Review by ahmadilham — COMMENTED** [review]
I believe this PR is still in progress because I don't see `Conclusion` part and Tech News list 
image

If you need any reference for content, please check any markdown in `_posts` folder https://github.com/Polyrific-Inc/tech-updates-dev/blob/main/_posts/2023-17-03-week11-2023.markdown

**Comment by muhammad-zulfa** [comment]
> I believe this PR is still in progress because I don't see `Conclusion` part and Tech News list image
> 
> If you need any reference for content, please check any markdown in `_posts` folder https://github.com/Polyrific-Inc/tech-updates-dev/blob/main/_posts/2023-17-03-week11-2023.markdown

conclussion itu masih masuk body ya mas @ahmadilham ?

**Comment by ahmadilham** [comment]
Yes, it is included in the body @muhammad-zulfa

**Review by ahmadilham — APPROVED** [review]
LGTM

**Pull request merged**
